//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1
        ///0,&quot;&quot;
        ///1,&quot;normal/Battle Start&quot;
        ///2,&quot;normal/Battle End&quot;
        ///3,&quot;normal/Idle&quot;
        ///4,&quot;normal/Idle inactive 1&quot;
        ///5,&quot;normal/idle inactive 2&quot;
        ///6,&quot;normal/idle inactive 3&quot;
        ///7,&quot;normal/Turning Left&quot;
        ///8,&quot;normal/Turning Right&quot;
        ///9,&quot;&quot;
        ///10,&quot;&quot;
        ///11,&quot;&quot;
        ///12,&quot;&quot;
        ///13,&quot;normal/Walking&quot;
        ///14,&quot;normal/Walking Left&quot;
        ///15,&quot;normal/Walking Right&quot;
        ///16,&quot;normal/Walking Back&quot;
        ///17,&quot;normal/Walk Start&quot;
        ///18,&quot;normal/Walk Start Right&quot;
        ///19,&quot;normal/Walk Start Left&quot;
        ///20,&quot;normal/walk_end_l&quot;
        ///21,&quot;&quot;
        ///22,&quot;normal/Run&quot;
        ///23,&quot;normal/Run Lef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string actiontimeline {
            get {
                return ResourceManager.GetString("actiontimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x0],2 [STRING(0x0)][0x0],3
        ///0,&quot;Default&quot;,&quot;Current Location BGM playing&quot;,&quot;&quot;
        ///1,&quot;N/A&quot;,&quot;N/A&quot;,&quot;&quot;
        ///2,&quot;Prelude ~ Rebirth&quot;,&quot;Start-up (ARR)&quot;,&quot;Intro/Title music&quot;
        ///3,&quot;Dreams Aloft&quot;,&quot;1.0/Old launcher theme&quot;,&quot;Heroic-ish music is in game&quot;
        ///4,&quot;Prelude ~ Discoveries&quot;,&quot;Character Select&quot;,&quot;Character Creation&quot;
        ///5,&quot;Behind Closed Doors&quot;,&quot;Inn&quot;,&quot;&quot;
        ///6,&quot;Wailers and Waterwheels&quot;,&quot;Gridania&quot;,&quot;Daytime Theme&quot;
        ///7,&quot;Dance of the Fireflies&quot;,&quot;Gridania&quot;,&quot;Nighttime Theme&quot;
        ///8,&quot;Serenity&quot;,&quot;Central/North  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BGM {
            get {
                return ResourceManager.GetString("BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] human {
            get {
                object obj = ResourceManager.GetObject("human", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1
        ///0,&quot;Player&quot;
        ///1,&quot;Chocobo&quot;
        ///2,&quot;Magitek Reaper&quot;
        ///3,&quot;Amalj&apos;aa&quot;
        ///4,&quot;Ixal&quot;
        ///5,&quot;Kobold&quot;
        ///6,&quot;Goblin&quot;
        ///7,&quot;Sylph&quot;
        ///8,&quot;Moogle&quot;
        ///9,&quot;Sahagin&quot;
        ///10,&quot;Mamool Ja Warrior&quot;
        ///11,&quot;Hecatonchier&quot;
        ///12,&quot;Giant&quot;
        ///13,&quot;Gigas&quot;
        ///14,&quot;Qiqirn&quot;
        ///15,&quot;Delivery Moogle&quot;
        ///16,&quot;Lamia&quot;
        ///17,&quot;Skeleton&quot;
        ///18,&quot;Succubus&quot;
        ///19,&quot;Demon&quot;
        ///20,&quot;Miteling&quot;
        ///21,&quot;Diremite&quot;
        ///22,&quot;Banemite&quot;
        ///23,&quot;Graffias&quot;
        ///24,&quot;Rat&quot;
        ///25,&quot;Squirrel&quot;
        ///26,&quot;Marmot&quot;
        ///27,&quot;Dormouse&quot;
        ///28,&quot;Funguar&quot;
        ///29,&quot;Myconid&quot;
        ///30,&quot;Funguar C (Blue)&quot;
        ///31,&quot;Galago&quot;
        ///32,&quot;Lemur&quot;
        ///33,&quot;Gala [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonsterList {
            get {
                return ResourceManager.GetString("MonsterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nope {
            get {
                object obj = ResourceManager.GetObject("Nope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index,0 [STRING(0x0)][0x0],1 [STRING(0x0)][0x0],2
        ///0,&quot;Target&quot;,&quot;9001,228,1,0&quot;
        ///1,&quot;Japanese Fan&quot;,&quot;9001,227,1,0&quot;
        ///2,&quot;Japanese Bell&quot;,&quot;9001,226,1,0&quot;
        ///3,&quot;Zenos Katana&quot;,&quot;9001,225,1,0&quot;
        ///4,&quot;Necklace&quot;,&quot;9001,224,1,0&quot;
        ///5,&quot;Corked Rose Alcohol Bottle&quot;,&quot;9001,222,1,0&quot;
        ///6,&quot;Corked Alcohol Bottle&quot;,&quot;9001,221,1,0&quot;
        ///7,&quot;Sparrow Taiyaki&quot;,&quot;9001,219,1,0&quot;
        ///8,&quot;Bom Boko Taiyaki&quot;,&quot;9001,218,1,0&quot;
        ///9,&quot;Odder Otter Taiyaki&quot;,&quot;9001,217,1,0&quot;
        ///10,&quot;BIG TUNA&quot;,&quot;9001,216,1,0&quot;
        ///11,&quot;Bamboo Blowgun&quot;,&quot;9001,212,1,0&quot;
        ///12,&quot;Papers&quot;,&quot;9001,211,1,0&quot;
        ///13,&quot;Spoon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropsList {
            get {
                return ResourceManager.GetString("PropsList", resourceCulture);
            }
        }
    }
}
