//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptMatrix.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlyOutStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlyOutStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptMatrix.Resx.FlyOutStrings", typeof(FlyOutStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACN.
        /// </summary>
        internal static string ACN {
            get {
                return ResourceManager.GetString("ACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALC.
        /// </summary>
        internal static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Classes.
        /// </summary>
        internal static string AllClasses {
            get {
                return ResourceManager.GetString("AllClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance Only.
        /// </summary>
        internal static string AppearanceOnly {
            get {
                return ResourceManager.GetString("AppearanceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARC.
        /// </summary>
        internal static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AST.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        internal static string Battle {
            get {
                return ResourceManager.GetString("Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGM.
        /// </summary>
        internal static string BGM {
            get {
                return ResourceManager.GetString("BGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLM.
        /// </summary>
        internal static string BLM {
            get {
                return ResourceManager.GetString("BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRD.
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSM.
        /// </summary>
        internal static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTN.
        /// </summary>
        internal static string BTN {
            get {
                return ResourceManager.GetString("BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNJ.
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Selector.
        /// </summary>
        internal static string ColorSelector {
            get {
                return ResourceManager.GetString("ColorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRP.
        /// </summary>
        internal static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUL.
        /// </summary>
        internal static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciple of the Hand.
        /// </summary>
        internal static string DiscipleofHand {
            get {
                return ResourceManager.GetString("DiscipleofHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciple of the Land.
        /// </summary>
        internal static string DiscipleOfLand {
            get {
                return ResourceManager.GetString("DiscipleOfLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciple of Magic.
        /// </summary>
        internal static string DiscipleOfMagic {
            get {
                return ResourceManager.GetString("DiscipleOfMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciple of War.
        /// </summary>
        internal static string DiscipleOfWar {
            get {
                return ResourceManager.GetString("DiscipleOfWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciples of War or Magic.
        /// </summary>
        internal static string DisciplesOfWarMagic {
            get {
                return ResourceManager.GetString("DisciplesOfWarMagic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNC.
        /// </summary>
        internal static string DNC {
            get {
                return ResourceManager.GetString("DNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRG.
        /// </summary>
        internal static string DRG {
            get {
                return ResourceManager.GetString("DRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRK.
        /// </summary>
        internal static string DRK {
            get {
                return ResourceManager.GetString("DRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earing.
        /// </summary>
        internal static string Earing {
            get {
                return ResourceManager.GetString("Earing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes.
        /// </summary>
        internal static string Emotes {
            get {
                return ResourceManager.GetString("Emotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Only.
        /// </summary>
        internal static string EquipmentOnly {
            get {
                return ResourceManager.GetString("EquipmentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Selector.
        /// </summary>
        internal static string EquipmentSelector {
            get {
                return ResourceManager.GetString("EquipmentSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Paint.
        /// </summary>
        internal static string FacePaint {
            get {
                return ResourceManager.GetString("FacePaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacePaint Color.
        /// </summary>
        internal static string FacePaintColor {
            get {
                return ResourceManager.GetString("FacePaintColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facial Feature.
        /// </summary>
        internal static string FacialFeature {
            get {
                return ResourceManager.GetString("FacialFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Animation.
        /// </summary>
        internal static string ForceAnimation {
            get {
                return ResourceManager.GetString("ForceAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSH.
        /// </summary>
        internal static string FSH {
            get {
                return ResourceManager.GetString("FSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLA.
        /// </summary>
        internal static string GLA {
            get {
                return ResourceManager.GetString("GLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNB.
        /// </summary>
        internal static string GNB {
            get {
                return ResourceManager.GetString("GNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        internal static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Color.
        /// </summary>
        internal static string HairColor {
            get {
                return ResourceManager.GetString("HairColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Selector.
        /// </summary>
        internal static string HairSelector {
            get {
                return ResourceManager.GetString("HairSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        internal static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights Color.
        /// </summary>
        internal static string HighlightsColor {
            get {
                return ResourceManager.GetString("HighlightsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Animation.
        /// </summary>
        internal static string IdleAnimation {
            get {
                return ResourceManager.GetString("IdleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Everything.
        /// </summary>
        internal static string IncludeEverything {
            get {
                return ResourceManager.GetString("IncludeEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include OffHand.
        /// </summary>
        internal static string IncludeOffhand {
            get {
                return ResourceManager.GetString("IncludeOffhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Dyes.
        /// </summary>
        internal static string KeepDyes {
            get {
                return ResourceManager.GetString("KeepDyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-Eye Color.
        /// </summary>
        internal static string LeftEyeColor {
            get {
                return ResourceManager.GetString("LeftEyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Finger.
        /// </summary>
        internal static string LeftFinger {
            get {
                return ResourceManager.GetString("LeftFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limbal-Eye Color.
        /// </summary>
        internal static string LimbalEyeColor {
            get {
                return ResourceManager.GetString("LimbalEyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lip Color.
        /// </summary>
        internal static string LipColor {
            get {
                return ResourceManager.GetString("LipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LNC.
        /// </summary>
        internal static string LNC {
            get {
                return ResourceManager.GetString("LNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTW.
        /// </summary>
        internal static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Hand.
        /// </summary>
        internal static string MainHand {
            get {
                return ResourceManager.GetString("MainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCH.
        /// </summary>
        internal static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNK.
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model List.
        /// </summary>
        internal static string ModelList {
            get {
                return ResourceManager.GetString("ModelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Values.
        /// </summary>
        internal static string ModelValues {
            get {
                return ResourceManager.GetString("ModelValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string Monster {
            get {
                return ResourceManager.GetString("Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRD.
        /// </summary>
        internal static string MRD {
            get {
                return ResourceManager.GetString("MRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        internal static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIN.
        /// </summary>
        internal static string NIN {
            get {
                return ResourceManager.GetString("NIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Selector.
        /// </summary>
        internal static string NPCSelect {
            get {
                return ResourceManager.GetString("NPCSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Hand.
        /// </summary>
        internal static string OffHand {
            get {
                return ResourceManager.GetString("OffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGL.
        /// </summary>
        internal static string PGL {
            get {
                return ResourceManager.GetString("PGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLD.
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Props Main Hand.
        /// </summary>
        internal static string PropsMainHand {
            get {
                return ResourceManager.GetString("PropsMainHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Props Off Hand.
        /// </summary>
        internal static string PropsOffHand {
            get {
                return ResourceManager.GetString("PropsOffHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDM.
        /// </summary>
        internal static string RDM {
            get {
                return ResourceManager.GetString("RDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse FacePaint.
        /// </summary>
        internal static string ReverseFacePaint {
            get {
                return ResourceManager.GetString("ReverseFacePaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-Eye Color.
        /// </summary>
        internal static string RightEyeColor {
            get {
                return ResourceManager.GetString("RightEyeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Finger.
        /// </summary>
        internal static string RightFinger {
            get {
                return ResourceManager.GetString("RightFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROG.
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAM.
        /// </summary>
        internal static string SAM {
            get {
                return ResourceManager.GetString("SAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCH.
        /// </summary>
        internal static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        internal static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkinColor.
        /// </summary>
        internal static string SkinColor {
            get {
                return ResourceManager.GetString("SkinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMN.
        /// </summary>
        internal static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THM.
        /// </summary>
        internal static string THM {
            get {
                return ResourceManager.GetString("THM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAR.
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHM.
        /// </summary>
        internal static string WHM {
            get {
                return ResourceManager.GetString("WHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist.
        /// </summary>
        internal static string Wrist {
            get {
                return ResourceManager.GetString("Wrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WVR.
        /// </summary>
        internal static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
    }
}
