//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptMatrix.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MiscStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptMatrix.Resx.MiscStrings", typeof(MiscStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trainer and its base code was originally created by LeonBlade..
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the early ages of the trainer Johto took over, maintaining and updating the SSTools project..
        /// </summary>
        public static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later on Krisan Thyme began work on a new branch - CMTools - which has since been merged into the main repo..
        /// </summary>
        public static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to Goat and Seria Myouna for their contributions!.
        /// </summary>
        public static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is powered by MaterialDesignInXAML, MahApps, Fody, Newtonsoft.Json and Memory.dll.
        /// </summary>
        public static string About4 {
            get {
                return ResourceManager.GetString("About4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Options.
        /// </summary>
        public static string AdditionalOptions {
            get {
                return ResourceManager.GetString("AdditionalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language:.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage2 {
            get {
                return ResourceManager.GetString("ChangeLanguage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Matrix Directories.
        /// </summary>
        public static string CMDirectories {
            get {
                return ResourceManager.GetString("CMDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMTool Saving/Loading.
        /// </summary>
        public static string CMToolSaving {
            get {
                return ResourceManager.GetString("CMToolSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zodiark Theme.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Backgrounds.
        /// </summary>
        public static string DisableBackground {
            get {
                return ResourceManager.GetString("DisableBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to the Devs!.
        /// </summary>
        public static string DonateDevs {
            get {
                return ResourceManager.GetString("DonateDevs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel like you want to make a donation? It would be gratefully received. Click any of the buttons below to donate via Ko-fi..
        /// </summary>
        public static string DonateDevs2 {
            get {
                return ResourceManager.GetString("DonateDevs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to Johto.
        /// </summary>
        public static string DonateJohto {
            get {
                return ResourceManager.GetString("DonateJohto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to Krisan Thyme.
        /// </summary>
        public static string DonateKrisan {
            get {
                return ResourceManager.GetString("DonateKrisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to LeonBlade.
        /// </summary>
        public static string DonateLeon {
            get {
                return ResourceManager.GetString("DonateLeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Backgrounds.
        /// </summary>
        public static string EnableBackground {
            get {
                return ResourceManager.GetString("EnableBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset Saves:.
        /// </summary>
        public static string GearsetSaves {
            get {
                return ResourceManager.GetString("GearsetSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say hello, submit a feature request or raise a bug..
        /// </summary>
        public static string GetInTouch2 {
            get {
                return ResourceManager.GetString("GetInTouch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydaelyn Theme.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix Saves:.
        /// </summary>
        public static string MatrixSaves {
            get {
                return ResourceManager.GetString("MatrixSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proudly Open Source.
        /// </summary>
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is completely open source. If you like it and want to say thanks you could hit the GitHub Star button and message us your thanks..
        /// </summary>
        public static string OpenSource2 {
            get {
                return ResourceManager.GetString("OpenSource2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Saves:.
        /// </summary>
        public static string ProfileSaves {
            get {
                return ResourceManager.GetString("ProfileSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Explorer.
        /// </summary>
        public static string WindowsExplorer {
            get {
                return ResourceManager.GetString("WindowsExplorer", resourceCulture);
            }
        }
    }
}
