//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptMatrix.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIPoseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIPoseStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptMatrix.Resx.UIPoseStrings", typeof(UIPoseStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen:.
        /// </summary>
        public static string Abdomen {
            get {
                return ResourceManager.GetString("Abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Loading.
        /// </summary>
        public static string AdvancedLoading {
            get {
                return ResourceManager.GetString("AdvancedLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adv. Load CMP File.
        /// </summary>
        public static string AdvLoadCMPFile {
            get {
                return ResourceManager.GetString("AdvLoadCMPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms:.
        /// </summary>
        public static string Arms {
            get {
                return ResourceManager.GetString("Arms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back:.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body:.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body2 {
            get {
                return ResourceManager.GetString("Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body &amp; Clothes.
        /// </summary>
        public static string BodyClothes {
            get {
                return ResourceManager.GetString("BodyClothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breasts:.
        /// </summary>
        public static string Breasts {
            get {
                return ResourceManager.GetString("Breasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge:.
        /// </summary>
        public static string Bridge {
            get {
                return ResourceManager.GetString("Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brows:.
        /// </summary>
        public static string Brows {
            get {
                return ResourceManager.GetString("Brows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calves:.
        /// </summary>
        public static string Calves {
            get {
                return ResourceManager.GetString("Calves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cervical:.
        /// </summary>
        public static string Cervical {
            get {
                return ResourceManager.GetString("Cervical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheeks:.
        /// </summary>
        public static string Cheeks {
            get {
                return ResourceManager.GetString("Cheeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clavicles:.
        /// </summary>
        public static string Clavicles {
            get {
                return ResourceManager.GetString("Clavicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes:.
        /// </summary>
        public static string Clothes {
            get {
                return ResourceManager.GetString("Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes.
        /// </summary>
        public static string Clothes2 {
            get {
                return ResourceManager.GetString("Clothes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couters:.
        /// </summary>
        public static string Couters {
            get {
                return ResourceManager.GetString("Couters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Tertiary Bones.
        /// </summary>
        public static string DetectTertiaryBones {
            get {
                return ResourceManager.GetString("DetectTertiaryBones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings:.
        /// </summary>
        public static string Earrings {
            get {
                return ResourceManager.GetString("Earrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earrings.
        /// </summary>
        public static string Earrings2 {
            get {
                return ResourceManager.GetString("Earrings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ears:.
        /// </summary>
        public static string Ears {
            get {
                return ResourceManager.GetString("Ears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elbows:.
        /// </summary>
        public static string Elbows {
            get {
                return ResourceManager.GetString("Elbows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing:.
        /// </summary>
        public static string EnableEditing {
            get {
                return ResourceManager.GetString("EnableEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable GPose to use this feature..
        /// </summary>
        public static string EnableGpose {
            get {
                return ResourceManager.GetString("EnableGpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Physics:.
        /// </summary>
        public static string EnablePhysics {
            get {
                return ResourceManager.GetString("EnablePhysics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip &amp; Other.
        /// </summary>
        public static string EquipOther {
            get {
                return ResourceManager.GetString("EquipOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyebrows:.
        /// </summary>
        public static string Eyebrows {
            get {
                return ResourceManager.GetString("Eyebrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyelids:.
        /// </summary>
        public static string Eyelids {
            get {
                return ResourceManager.GetString("Eyelids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyes:.
        /// </summary>
        public static string Eyes {
            get {
                return ResourceManager.GetString("Eyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face:.
        /// </summary>
        public static string Face {
            get {
                return ResourceManager.GetString("Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet:.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forearms:.
        /// </summary>
        public static string Forearms {
            get {
                return ResourceManager.GetString("Forearms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front:.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General:.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair:.
        /// </summary>
        public static string Hair {
            get {
                return ResourceManager.GetString("Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        public static string Hair2 {
            get {
                return ResourceManager.GetString("Hair2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair &amp; Accessories.
        /// </summary>
        public static string HairAccessories {
            get {
                return ResourceManager.GetString("HairAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands:.
        /// </summary>
        public static string Hands {
            get {
                return ResourceManager.GetString("Hands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        public static string Hands2 {
            get {
                return ResourceManager.GetString("Hands2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands &amp; Legs.
        /// </summary>
        public static string HandsLegs {
            get {
                return ResourceManager.GetString("HandsLegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head:.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string Head2 {
            get {
                return ResourceManager.GetString("Head2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head &amp; Hair.
        /// </summary>
        public static string HeadHair {
            get {
                return ResourceManager.GetString("HeadHair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm:.
        /// </summary>
        public static string Helm {
            get {
                return ResourceManager.GetString("Helm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helm.
        /// </summary>
        public static string Helm2 {
            get {
                return ResourceManager.GetString("Helm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holsters:.
        /// </summary>
        public static string Holsters {
            get {
                return ResourceManager.GetString("Holsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrothgar Whiskers:.
        /// </summary>
        public static string HrothgarWhiskers {
            get {
                return ResourceManager.GetString("HrothgarWhiskers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index:.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw:.
        /// </summary>
        public static string Jaw {
            get {
                return ResourceManager.GetString("Jaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knees:.
        /// </summary>
        public static string Knees {
            get {
                return ResourceManager.GetString("Knees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arm:.
        /// </summary>
        public static string LeftArm {
            get {
                return ResourceManager.GetString("LeftArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arm.
        /// </summary>
        public static string LeftArm2 {
            get {
                return ResourceManager.GetString("LeftArm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand:.
        /// </summary>
        public static string LeftHand {
            get {
                return ResourceManager.GetString("LeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand.
        /// </summary>
        public static string LeftHand2 {
            get {
                return ResourceManager.GetString("LeftHand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Leg:.
        /// </summary>
        public static string LeftLeg {
            get {
                return ResourceManager.GetString("LeftLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Leg.
        /// </summary>
        public static string LeftLeg2 {
            get {
                return ResourceManager.GetString("LeftLeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs:.
        /// </summary>
        public static string Legs {
            get {
                return ResourceManager.GetString("Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load CMP File.
        /// </summary>
        public static string LoadCMPFile {
            get {
                return ResourceManager.GetString("LoadCMPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Pose from a user-generated CMP file..
        /// </summary>
        public static string LoadCMPToolTip {
            get {
                return ResourceManager.GetString("LoadCMPToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Lids:.
        /// </summary>
        public static string LowerLids {
            get {
                return ResourceManager.GetString("LowerLids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Lip:.
        /// </summary>
        public static string LowerLip {
            get {
                return ResourceManager.GetString("LowerLip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumbar:.
        /// </summary>
        public static string Lumbar {
            get {
                return ResourceManager.GetString("Lumbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle:.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth:.
        /// </summary>
        public static string Mouth {
            get {
                return ResourceManager.GetString("Mouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck:.
        /// </summary>
        public static string Neck {
            get {
                return ResourceManager.GetString("Neck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose:.
        /// </summary>
        public static string Nose {
            get {
                return ResourceManager.GetString("Nose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauldrons:.
        /// </summary>
        public static string Pauldrons {
            get {
                return ResourceManager.GetString("Pauldrons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinky:.
        /// </summary>
        public static string Pinky {
            get {
                return ResourceManager.GetString("Pinky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poleyns:.
        /// </summary>
        public static string Poleyns {
            get {
                return ResourceManager.GetString("Poleyns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pose Matrix Settings.
        /// </summary>
        public static string PoseMatrixSettings {
            get {
                return ResourceManager.GetString("PoseMatrixSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime Rotation.
        /// </summary>
        public static string RealTimeRotation {
            get {
                return ResourceManager.GetString("RealTimeRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your mouse buttons to control the cube.
        ///
        ///• All rotations are relative to the direction that the entity is currently facing:
        ///
        ///• RMB controls X-axis rotation.
        ///
        ///• LMB controls Y-axis rotation.
        ///
        ///• MMB controls Z-axis rotation..
        /// </summary>
        public static string RealTimeRotationToolTip {
            get {
                return ResourceManager.GetString("RealTimeRotationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arm:.
        /// </summary>
        public static string RightArm {
            get {
                return ResourceManager.GetString("RightArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arm.
        /// </summary>
        public static string RightArm2 {
            get {
                return ResourceManager.GetString("RightArm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand:.
        /// </summary>
        public static string RightHand {
            get {
                return ResourceManager.GetString("RightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand.
        /// </summary>
        public static string RightHand2 {
            get {
                return ResourceManager.GetString("RightHand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Leg:.
        /// </summary>
        public static string RightLeg {
            get {
                return ResourceManager.GetString("RightLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Leg.
        /// </summary>
        public static string RightLeg2 {
            get {
                return ResourceManager.GetString("RightLeg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring:.
        /// </summary>
        public static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root:.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Sliders:.
        /// </summary>
        public static string RotationSliders {
            get {
                return ResourceManager.GetString("RotationSliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This toggle will switch between Rotation Sliders and Numerical direct input.
        ///• Turning it off will turn the XYZ Rotation sliders into numerical values.
        ///• Each input will accept a value between 0 and 360..
        /// </summary>
        public static string RotationSlidersToolTip {
            get {
                return ResourceManager.GetString("RotationSlidersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CMP File.
        /// </summary>
        public static string SaveCMPFile {
            get {
                return ResourceManager.GetString("SaveCMPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pose to a CMP file..
        /// </summary>
        public static string SaveCMPToolTip {
            get {
                return ResourceManager.GetString("SaveCMPToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Load.
        /// </summary>
        public static string SaveLoad {
            get {
                return ResourceManager.GetString("SaveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scabbards:.
        /// </summary>
        public static string Scabbards {
            get {
                return ResourceManager.GetString("Scabbards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheathes:.
        /// </summary>
        public static string Sheathes {
            get {
                return ResourceManager.GetString("Sheathes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shields:.
        /// </summary>
        public static string Shields {
            get {
                return ResourceManager.GetString("Shields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulders:.
        /// </summary>
        public static string Shoulders {
            get {
                return ResourceManager.GetString("Shoulders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sides:.
        /// </summary>
        public static string Sides {
            get {
                return ResourceManager.GetString("Sides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Saving &amp; Loading.
        /// </summary>
        public static string StandardSaving {
            get {
                return ResourceManager.GetString("StandardSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail:.
        /// </summary>
        public static string Tail {
            get {
                return ResourceManager.GetString("Tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Race, Hair, and Equipment exclusive Bones for the selected actor..
        /// </summary>
        public static string TertiaryButtonToolTip {
            get {
                return ResourceManager.GetString("TertiaryButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoracic:.
        /// </summary>
        public static string Thoracic {
            get {
                return ResourceManager.GetString("Thoracic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw:.
        /// </summary>
        public static string Throw {
            get {
                return ResourceManager.GetString("Throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumb:.
        /// </summary>
        public static string Thumb {
            get {
                return ResourceManager.GetString("Thumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toes:.
        /// </summary>
        public static string Toes {
            get {
                return ResourceManager.GetString("Toes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Helm Parenting.
        /// </summary>
        public static string ToggleHelmParenting {
            get {
                return ResourceManager.GetString("ToggleHelmParenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top2 {
            get {
                return ResourceManager.GetString("Top2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique:.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown:.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Lip:.
        /// </summary>
        public static string UpperLip {
            get {
                return ResourceManager.GetString("UpperLip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viera Ears:.
        /// </summary>
        public static string VieraEars {
            get {
                return ResourceManager.GetString("VieraEars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist:.
        /// </summary>
        public static string Waist {
            get {
                return ResourceManager.GetString("Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        public static string Waist2 {
            get {
                return ResourceManager.GetString("Waist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist &amp; Legs.
        /// </summary>
        public static string WaistLegs {
            get {
                return ResourceManager.GetString("WaistLegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons:.
        /// </summary>
        public static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon:.
        /// </summary>
        public static string Weapons2 {
            get {
                return ResourceManager.GetString("Weapons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        public static string Weapons3 {
            get {
                return ResourceManager.GetString("Weapons3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrists:.
        /// </summary>
        public static string Wrists {
            get {
                return ResourceManager.GetString("Wrists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Rotation:.
        /// </summary>
        public static string XRot {
            get {
                return ResourceManager.GetString("XRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the X Rotation of the selected joint..
        /// </summary>
        public static string XRotToolTip {
            get {
                return ResourceManager.GetString("XRotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Rotation:.
        /// </summary>
        public static string YRot {
            get {
                return ResourceManager.GetString("YRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Y Rotation of the selected joint..
        /// </summary>
        public static string YRotToolTip {
            get {
                return ResourceManager.GetString("YRotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Rotation:.
        /// </summary>
        public static string ZRot {
            get {
                return ResourceManager.GetString("ZRot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifies the Z Rotation of the selected joint..
        /// </summary>
        public static string ZRotToolTip {
            get {
                return ResourceManager.GetString("ZRotToolTip", resourceCulture);
            }
        }
    }
}
