//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptMatrix.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptMatrix.Resx.WindowsStrings", typeof(WindowsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Save Window.
        /// </summary>
        internal static string CharacterSaveWindow {
            get {
                return ResourceManager.GetString("CharacterSaveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearset Name.
        /// </summary>
        internal static string GearsetName {
            get {
                return ResourceManager.GetString("GearsetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure ffxiv_dx11.exe is running!.
        /// </summary>
        internal static string IsDx11Running {
            get {
                return ResourceManager.GetString("IsDx11Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All[Appearance].
        /// </summary>
        internal static string LoadAllAppearance {
            get {
                return ResourceManager.GetString("LoadAllAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All Character.
        /// </summary>
        internal static string LoadAllCharacter {
            get {
                return ResourceManager.GetString("LoadAllCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All[Equipment].
        /// </summary>
        internal static string LoadAllEquipment {
            get {
                return ResourceManager.GetString("LoadAllEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load .Dat.
        /// </summary>
        internal static string LoadDat {
            get {
                return ResourceManager.GetString("LoadDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Gearset.
        /// </summary>
        internal static string LoadGearset {
            get {
                return ResourceManager.GetString("LoadGearset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Window.
        /// </summary>
        internal static string LoadWindow {
            get {
                return ResourceManager.GetString("LoadWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Finder.
        /// </summary>
        internal static string ProcessFinder {
            get {
                return ResourceManager.GetString("ProcessFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Gearset.
        /// </summary>
        internal static string SaveGearset {
            get {
                return ResourceManager.GetString("SaveGearset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Name.
        /// </summary>
        internal static string SaveName {
            get {
                return ResourceManager.GetString("SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Gearset name here....
        /// </summary>
        internal static string SearchGearSet {
            get {
                return ResourceManager.GetString("SearchGearSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Save name here.....
        /// </summary>
        internal static string SearchSaveName {
            get {
                return ResourceManager.GetString("SearchSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Explorer:.
        /// </summary>
        internal static string UseWindowsEx {
            get {
                return ResourceManager.GetString("UseWindowsEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Gearset name here....
        /// </summary>
        internal static string WriteGearsetName {
            get {
                return ResourceManager.GetString("WriteGearsetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
